const data = () => {
return [
    {
      sku_id: 5745999057942,
      spec_id: "558a5629e92012339aaca780b2ea41ca",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑蓝",
          value_trans: "男士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN015xdGyV1Njb7TG8Z8Y_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "S",
          value_trans: "S",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057943,
      spec_id: "3985999831de3c2025dc82f03e8635f8",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑蓝",
          value_trans: "男士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN015xdGyV1Njb7TG8Z8Y_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "M",
          value_trans: "M",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057944,
      spec_id: "87a70be52557a93b85c03108c1c68d6a",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑蓝",
          value_trans: "男士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN015xdGyV1Njb7TG8Z8Y_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "L",
          value_trans: "L",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057945,
      spec_id: "f37b533df305cf655e052229d3910a30",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑蓝",
          value_trans: "男士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN015xdGyV1Njb7TG8Z8Y_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XL",
          value_trans: "XL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057946,
      spec_id: "587c1a604342ef72ff2a29104408401d",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑蓝",
          value_trans: "男士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN015xdGyV1Njb7TG8Z8Y_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXL",
          value_trans: "XXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057947,
      spec_id: "69396ca55d07f75a0eade14f015971df",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑蓝",
          value_trans: "男士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN015xdGyV1Njb7TG8Z8Y_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXXL",
          value_trans: "XXXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057948,
      spec_id: "b4ba7d274e46cb1f33b1fd11fec76bfd",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰银",
          value_trans: "男士短袖灰银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01Ec3PX41Njb7RSztG0_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "S",
          value_trans: "S",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057949,
      spec_id: "249fd6f3daa2ff2eba423d89aa84e5d8",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰银",
          value_trans: "男士短袖灰银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01Ec3PX41Njb7RSztG0_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "M",
          value_trans: "M",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057950,
      spec_id: "2a2ede574189664c9c57eb53abdbc965",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰银",
          value_trans: "男士短袖灰银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01Ec3PX41Njb7RSztG0_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "L",
          value_trans: "L",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057951,
      spec_id: "7d038d860987397bcd9b0f2d42b28ffb",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰银",
          value_trans: "男士短袖灰银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01Ec3PX41Njb7RSztG0_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XL",
          value_trans: "XL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057952,
      spec_id: "ebadc26e6bd14cb9b625939efd04d9ea",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰银",
          value_trans: "男士短袖灰银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01Ec3PX41Njb7RSztG0_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXL",
          value_trans: "XXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057953,
      spec_id: "55f4e4148954622ce3dc89a2f94fc69e",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰银",
          value_trans: "男士短袖灰银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01Ec3PX41Njb7RSztG0_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXXL",
          value_trans: "XXXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057954,
      spec_id: "b5abf791aab9ba66e0c89055d8787901",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑银",
          value_trans: "男士短袖黑银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01DyTskH1Njb7TgEKTB_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "S",
          value_trans: "S",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057955,
      spec_id: "99e41c2277a69937dea9c82505ef0c4e",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑银",
          value_trans: "男士短袖黑银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01DyTskH1Njb7TgEKTB_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "M",
          value_trans: "M",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057956,
      spec_id: "7ff284c3d19b822145f48d7161010bad",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑银",
          value_trans: "男士短袖黑银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01DyTskH1Njb7TgEKTB_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "L",
          value_trans: "L",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057957,
      spec_id: "ac1d29d6db76cc64fe1dd105691e6d0b",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑银",
          value_trans: "男士短袖黑银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01DyTskH1Njb7TgEKTB_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XL",
          value_trans: "XL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057958,
      spec_id: "b0a072134718e9744c1673b0839228a9",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑银",
          value_trans: "男士短袖黑银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01DyTskH1Njb7TgEKTB_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXL",
          value_trans: "XXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057959,
      spec_id: "da6f4337cb1f4b069999dfa5d6869c3e",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑银",
          value_trans: "男士短袖黑银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01DyTskH1Njb7TgEKTB_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXXL",
          value_trans: "XXXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057960,
      spec_id: "14d371c46fcfbd0b325c034eaf578176",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰蓝",
          value_trans: "男士短袖灰蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01rUh3Fq1Njb7Sq6s13_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "S",
          value_trans: "S",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057961,
      spec_id: "ca689283297a405c2772fca776561edc",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰蓝",
          value_trans: "男士短袖灰蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01rUh3Fq1Njb7Sq6s13_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "M",
          value_trans: "M",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057962,
      spec_id: "6a22d5bd08aeadcdd07f9093d3d901ed",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰蓝",
          value_trans: "男士短袖灰蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01rUh3Fq1Njb7Sq6s13_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "L",
          value_trans: "L",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057963,
      spec_id: "20348d0c42a99e9ead2205e1e70a3e52",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰蓝",
          value_trans: "男士短袖灰蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01rUh3Fq1Njb7Sq6s13_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XL",
          value_trans: "XL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057964,
      spec_id: "0f429a553d56b8997f31a4f8d9b8caaa",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰蓝",
          value_trans: "男士短袖灰蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01rUh3Fq1Njb7Sq6s13_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXL",
          value_trans: "XXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057965,
      spec_id: "89d8bb305821722c6d2fae1059929597",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖灰蓝",
          value_trans: "男士短袖灰蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01rUh3Fq1Njb7Sq6s13_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXXL",
          value_trans: "XXXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057966,
      spec_id: "5cd9561d5ed0614eace42402adc59026",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖白银",
          value_trans: "男士短袖白银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN017JprqX1Njb7TWxGJR_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "S",
          value_trans: "S",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057967,
      spec_id: "642ea6b8edab42081c50f82a87d1f784",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖白银",
          value_trans: "男士短袖白银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN017JprqX1Njb7TWxGJR_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "M",
          value_trans: "M",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057968,
      spec_id: "cb54fc79b52f97d678582c31cd71798a",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖白银",
          value_trans: "男士短袖白银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN017JprqX1Njb7TWxGJR_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "L",
          value_trans: "L",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057969,
      spec_id: "9ef0c15c694c89fb1ed797c47fba6610",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖白银",
          value_trans: "男士短袖白银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN017JprqX1Njb7TWxGJR_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XL",
          value_trans: "XL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057970,
      spec_id: "14abfb056f1c4101a089e1520e331cff",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖白银",
          value_trans: "男士短袖白银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN017JprqX1Njb7TWxGJR_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXL",
          value_trans: "XXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057971,
      spec_id: "20ec27e816485baff7d30ae3555a134d",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖白银",
          value_trans: "男士短袖白银",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN017JprqX1Njb7TWxGJR_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXXL",
          value_trans: "XXXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057972,
      spec_id: "3417df8c41a68a0b9bee2cf8063daa23",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑金",
          value_trans: "男士短袖黑金",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01kH5lLu1Njb7THcQYM_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "S",
          value_trans: "S",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057973,
      spec_id: "b2cabb2e1f2267eece4f7bd4f29175c4",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑金",
          value_trans: "男士短袖黑金",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01kH5lLu1Njb7THcQYM_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "M",
          value_trans: "M",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057974,
      spec_id: "6f5cd532b28cdf9a5e06568bb2074184",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑金",
          value_trans: "男士短袖黑金",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01kH5lLu1Njb7THcQYM_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "L",
          value_trans: "L",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057975,
      spec_id: "55bbe903e9544234ea11c29905091a59",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑金",
          value_trans: "男士短袖黑金",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01kH5lLu1Njb7THcQYM_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XL",
          value_trans: "XL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057976,
      spec_id: "b205fc1134e6d377101c1ff49ec91d30",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑金",
          value_trans: "男士短袖黑金",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01kH5lLu1Njb7THcQYM_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXL",
          value_trans: "XXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057977,
      spec_id: "81f0619a37565bd6c2ea78c038f177d0",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "男士短袖黑金",
          value_trans: "男士短袖黑金",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01kH5lLu1Njb7THcQYM_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXXL",
          value_trans: "XXXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057978,
      spec_id: "a6ea52108b1152ec13aab213f71f9dcc",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "女士短袖黑蓝",
          value_trans: "女士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01q64NSv1Njb7T86MfN_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "S",
          value_trans: "S",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057979,
      spec_id: "f9ad81178370a3aa69cb702fe0f8a7b1",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "女士短袖黑蓝",
          value_trans: "女士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01q64NSv1Njb7T86MfN_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "M",
          value_trans: "M",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057980,
      spec_id: "06d5a9de2046ea664ce784c2f0cc83c5",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "女士短袖黑蓝",
          value_trans: "女士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01q64NSv1Njb7T86MfN_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "L",
          value_trans: "L",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057981,
      spec_id: "2a66a51b24c6c019517f088773742ccc",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "女士短袖黑蓝",
          value_trans: "女士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01q64NSv1Njb7T86MfN_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XL",
          value_trans: "XL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057982,
      spec_id: "71508c30af4df5eac6720782a39932a8",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "女士短袖黑蓝",
          value_trans: "女士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01q64NSv1Njb7T86MfN_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXL",
          value_trans: "XXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
    {
      sku_id: 5745999057983,
      spec_id: "842b10c970c4af96ed552b6962f03d6b",
      amount_on_sale: 9999,
      consign_price: 20,
      cargo_number: "",
      one_piece_price: null,
      offer_price: 20,
      attributes: [
        {
          attribute_id: 3216,
          attribute_name: "颜色",
          attribute_name_trans: "颜色",
          value: "女士短袖黑蓝",
          value_trans: "女士短袖黑蓝",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url:
            "https://cbu01.alicdn.com/img/ibank/O1CN01q64NSv1Njb7T86MfN_!!2219438891606-0-cib.jpg",
        },
        {
          attribute_id: 450,
          attribute_name: "尺码",
          attribute_name_trans: "尺码",
          value: "XXXL",
          value_trans: "XXXL",
          value_trans_ar: null,
          value_trans_en: null,
          sku_image_url: null,
        },
      ],
    },
  ];
}

  export default data;