import { StyleSheet, Platform } from "react-native";
import fontSize from "../../utils/fontsizeUtils";
import widthUtils from "../../utils/widthUtils";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#fff",
  },
  safeAreaContent: {
    flex: 1,
    paddingTop: 0,
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerRightSpace: {
    width: 40,
    height: 40,
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  shoppingCartLayout: {
    flex: 1,
    backgroundColor: "white",
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContentContainer: {
    paddingBottom: widthUtils(100, 100).height,
  },
  productListingContainer: {
    paddingTop: 3,
    paddingLeft: 16,
    paddingRight: 16,
  },

  shoppingCartSection: {
    marginTop: 14,
  },
  productCardContainer7: {
    flexDirection: "row",
    alignItems: "center",
  },
  iconContainer18: {
    width: widthUtils(18, 18).width,
    height: widthUtils(18, 18).height,
  },
  shoppingCartTitle: {
    marginLeft: 8,
    fontSize: fontSize(24),
    fontFamily: "Segoe UI",
    fontWeight: "600",
    color: "black",
  },
  productCardListing: {
    width: "100%",
    paddingRight: 4,
    paddingLeft: 16,
    marginTop: 16,
  },
  productCardContainer5: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  iconContainer24: {
    width: widthUtils(24, 24).width,
    height: widthUtils(24, 24).height,
  },
  imageThumbnail: {
    width: widthUtils(50, 50).width,
    height: widthUtils(50, 50).height,
    borderRadius: 5,
  },
  productInfoContainer2: {
    flex: 1,
    maxWidth: 288,
  },
  casualTextSnippet: {
    width: "100%",
    fontSize: fontSize(16),
    lineHeight: fontSize(18),
    fontFamily: "Segoe UI",
    color: "black",
    textAlign: "left",
  },
  productDetailsTextStyle1: {
    marginTop: 5,
    fontSize: fontSize(12),
    fontFamily: "Segoe UI",
    color: "#747474",
  },
  productCardContainer6: {
    width: "100%",
    marginTop: 11,
  },
  productCardContainer4: {
    marginTop: 12,
    marginBottom: 12,
  },
  productImageDisplayStyle: {
    width: widthUtils(40, 40).width,
    height: widthUtils(40, 40).height,
    borderRadius: 5,
  },
  productCardWidget1: {
    paddingBottom: 5,
    flex: 1,
  },
  longLifeRougeStyle: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    fontFamily: "Segoe UI",
    backgroundColor: "#f4f4f4",
    borderRadius: 16,
    alignSelf: "flex-start",
    maxWidth: widthUtils(249, 249).width,
    marginBottom: 4,
  },
  longLifeTextSnippet: {
    color: "#747474",
    fontSize: fontSize(11),
    lineHeight: fontSize(13),
    fontFamily: "Segoe UI",
  },
  productVariantButton: {
    width: widthUtils(24, 80).width,
    height: widthUtils(24, 80).height,
    fontSize: fontSize(16),
    fontFamily: "Segoe UI",
    color: "#747474",
    backgroundColor: "#f4f4f4",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  productCardContainer3: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    justifyContent: "flex-start",
  },
  productInfoContainer4: {
    width: widthUtils(76, 76).width,
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 3.75,
  },
  productInfoContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  productCodeLabel: {
    fontSize: fontSize(16),
    lineHeight: 22,
    fontFamily: "Segoe UI",
    fontWeight: "700",
    color: "#FF5100",
  },
  productDetailsTextStyle: {
    fontSize: fontSize(10),
    fontFamily: "Segoe UI",
    fontWeight: "700",
    color: "#FF5100",
    lineHeight: fontSize(13),
    marginLeft: 3,
  },
  productInfoContainer1: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 3.75,
    marginBottom: 2,
  },
  priceInfoContainer1: {
    paddingTop: 10,
    paddingBottom: 5,
  },
  discountPriceLabel: {
    fontSize: fontSize(12),
    fontFamily: "PingFang SC",
    fontWeight: "600",
    color: "#9a9a9a",
    textDecorationLine: "line-through",
  },
  vipContainer: {
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
  },
  vipImage: {
    width: widthUtils(28, 28).width,
    height: widthUtils(28, 28).height,
  },
  discountPercentageTextStyle: {
    position: "absolute",
    fontSize: fontSize(12),
    fontFamily: "Segoe UI",
    fontWeight: "900",
    fontStyle: "italic",
    color: "#4e2000",
    textAlign: "center",
  },
  borderBoxDivider: {
    width: "100%",
    marginTop: -4.75,
    borderTopWidth: 1,
    borderTopColor: "#9a9a9a",
  },
  discountInfoContainer1: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 3.25,
    width: widthUtils(22, 22).width,
    height: widthUtils(22, 22).height,
  },
  iconContainer32: {
    width: widthUtils(32, 32).width,
    height: widthUtils(32, 32).height,
    marginTop: -26,
  },
  priceSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  orderQuantityContainer: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    marginRight: 10,
    justifyContent: "flex-end",
    minWidth: 100,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#f3f4f8",
    backgroundColor: "#fff",
    overflow: "visible",
  },
  borderBoxDivider1: {
    width: widthUtils(9, 9).width,
    borderTopWidth: 1,
    borderTopColor: "black",
  },
  iconContainer12: {
    width: widthUtils(12, 12).width,
    height: widthUtils(12, 12).height,
  },
  quantityButton: {
    width: widthUtils(30, 30).width,
    height: widthUtils(30, 30).height,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: widthUtils(30, 30).width / 2,
  },
  quantityLabelContainer: {
    width: widthUtils(30, 30).width,
    height: widthUtils(30, 30).height,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    fontSize: fontSize(12),
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderLeftColor: "white",
    borderRightColor: "white",
    padding: 0,
    lineHeight: fontSize(12),
    borderRadius: 0,
  },
  flexDivider: {
    height: widthUtils(8, 8).height,
    width: "120%",
    marginLeft: -20,
  },
  fixedBottomContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "white",
  },
  iconContainer: {
    width: widthUtils(24, 24).width,
    height: widthUtils(24, 24).height,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
  },
  selectedIconContainer: {
    backgroundColor: "#FF5100",
  },
  checkmark: {
    color: "white",
    fontSize: fontSize(16),
    fontWeight: "bold",
  },
  flexboxContainerWithButton: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "space-between",
    height: widthUtils(70, 70).height,
    paddingRight: 20,
    paddingLeft: 20,
    width: "100%",
  },
  headerTitle: {
    fontSize: fontSize(18),
    fontWeight: "600",
    color: "black",
    textAlign: "center",
    flex: 1,
  },
  bottomSelectAllText: {
    marginLeft: 7,
    fontSize: fontSize(14),
    fontWeight: "600",
    color: "black",
  },
  highlightedText1: {
    fontSize: fontSize(20),
    fontWeight: "500",
    color: "black",
  },
  priceLabel: {
    fontSize: fontSize(10),
    fontWeight: "700",
    color: "black",
    lineHeight: fontSize(13),
    marginTop: fontSize(-8),
  },
  submitButtonStyle: {
    width: widthUtils(50, 110).width,
    height: widthUtils(50, 110).height,
    minWidth: widthUtils(50, 110).width,
    marginLeft: 11.5,
    fontSize: fontSize(18),
    lineHeight: fontSize(22),
    fontWeight: "500",
    color: "white",
    backgroundColor: "#FF5100",
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  quantityText: {
    fontSize: fontSize(16),
    color: "#333",
    fontWeight: "600",
  },
  quantityInput: {
    width: "100%",
    height: 40,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 5,
    paddingHorizontal: 10,
    fontSize: fontSize(16),
    textAlign: "center",
  },
  quantityInputInline: {
    fontSize: fontSize(16),
    color: "#333",
    fontWeight: "600",
    textAlign: "center",
    backgroundColor: "#fff",
    borderColor: "#FF5100",
    borderWidth: 2,
  },
  priceColumnContainer: {
    flexDirection: "column",
    justifyContent: "center",
  },
  disabledButton: {
    opacity: 0.6,
  },
  disabledQuantityButton: {
    backgroundColor: "#f3f4f8",
    borderWidth: 1,
    borderColor: "#f3f4f8",
  },
  quantityButtonEnabled: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#f3f4f8",
  },
  quantityButtonDisabled: {
    backgroundColor: "#f3f4f8",
    borderWidth: 1,
    borderColor: "#f3f4f8",
  },
  quantityDisplayText: {
    fontSize: fontSize(14),
    fontWeight: "500",
    color: "#000",
  },
  quantityButtonText: {
    fontSize: fontSize(25),
    lineHeight: fontSize(25),
    fontWeight: "300",
    color: "#000",
  },
  quantityButtonDisabledText: {
    fontSize: fontSize(25),
    lineHeight: fontSize(25),
    fontWeight: "300",
    color: "#bdbdbd",
  },
  loginOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  blurContainer: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor:
      Platform.OS === "android" ? "rgba(255, 255, 255, 0.95)" : "transparent",
  },
  loginPromptContainer: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 40,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 0,
    maxWidth: "80%",
  },
  loginIcon: {
    width: 80,
    height: 80,
    marginBottom: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255, 111, 48, 0.1)",
    borderRadius: 40,
  },
  loginIconText: {
    fontSize: 40,
    fontWeight: "bold",
    color: "#FF5100",
  },
  loginPromptTitle: {
    fontSize: fontSize(24),
    fontWeight: "700",
    color: "#333",
    marginBottom: 10,
    textAlign: "center",
  },
  loginPromptSubtitle: {
    fontSize: fontSize(16),
    color: "#666",
    marginBottom: 30,
    textAlign: "center",
    lineHeight: fontSize(22),
  },
  loginButton: {
    backgroundColor: "#FF5100",
    paddingHorizontal: 40,
    paddingVertical: 15,
    borderRadius: 25,
    minWidth: 160,
  },
  loginButtonText: {
    color: "white",
    fontSize: fontSize(18),
    fontWeight: "700",
    textAlign: "center",
  },
  productGroupDivider: {
    height: 5,
    backgroundColor: "#f0f0f0",
    width: "100%",
  },
  productCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    marginHorizontal: 16,
    marginTop: 12,
    padding: 12,
  },
});

export const modalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  popup: {
    backgroundColor: "white",
    borderRadius: 10,
    paddingVertical: 27,
    paddingHorizontal: 20,
    alignItems: "center",
    gap: 21,
    width: "80%",
  },
  image: {
    width: 80,
    height: 80,
    borderRadius: 5,
    resizeMode: "cover",
  },
  promptText: {
    fontSize: 20,
    fontWeight: "600",
    color: "black",
    fontFamily: "Segoe UI",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    marginTop: 20,
    gap: 20,
  },
  cancelButton1: {
    minWidth: 120,
    height: 50,
    borderRadius: 30,
    backgroundColor: "#f2f3f5",
    justifyContent: "center",
    alignItems: "center",
  },
  confirmButton: {
    minWidth: 120,
    height: 50,
    borderRadius: 30,
    backgroundColor: "#FF5100",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 20,
  },
  cancelText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#333333",
    fontFamily: "Source Han Sans CN",
  },
  confirmText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#ffffff",
    fontFamily: "Source Han Sans CN",
  },
  warningIconContainer: {
    backgroundColor: "#FFF2E9",
    borderRadius: 20,
    padding: 12,
    marginBottom: 16,
    alignSelf: "center",
    width: 52,
    height: 52,
    justifyContent: "center",
    alignItems: "center",
  },
  warningIcon: {
    width: 32,
    height: 32,
  },
  minQuantityPopup: {
    width: "80%",
    padding: 24,
  },
  minQuantityText: {
    fontSize: fontSize(16),
    color: "#333",
    marginVertical: 16,
    textAlign: "center",
    lineHeight: fontSize(22),
    fontWeight: "500",
  },
  minQuantityButton: {
    width: "100%",
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FF5100",
    marginTop: 16,
  },
  minQuantityButtonText: {
    fontSize: fontSize(16),
    fontWeight: "600",
  },
});