import { StyleSheet, Platform } from "react-native";
import widthUtils from "../../utils/widthUtils";
import fontSize from "../../utils/fontsizeUtils";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#fff",
  },
  safeAreaContent: {
    flex: 1,
    paddingTop: Platform.OS === "android" ? 0 : 0,
  },
  flexColumnContainer1: {
    flex: 1,
  },
  timecardWidget: {
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "flex-start",
    width: "100%",
    height: widthUtils(272, 272).height,
    overflow: "hidden",
  },

  timeContainer1: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    height: widthUtils(43, 43).height,
    paddingTop: 21,
  },
  timeContainer2: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
    justifyContent: "space-between",
  },
  timeContainer: {
    display: "flex",
    flex: 1,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 153,
    paddingRight: 6,
    paddingLeft: 16,
  },
  timeDisplayStyle: {
    padding: 0,
    margin: 0,
    fontSize: fontSize(17),
    fontWeight: "600",
    fontFamily:
      "SF Pro, -apple-system, system-ui, BlinkMacSystemFont, sans-serif",
    color: "white",
  },
  timeDisplayContainer: {
    width: widthUtils(10, 124).width,
    height: widthUtils(10, 124).height,
  },
  timeDisplayContainer1: {
    flex: 1,
    width: widthUtils(13, 153).width,
    height: widthUtils(13, 153).height,
  },
  flexColumnContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "flex-start",
    paddingVertical: widthUtils(10, 10).height,
    paddingHorizontal: 20,
    paddingBottom: 3.5,
    flex: 1,
  },
  flexContainerWithImageAndText: {
    display: "flex",
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  flexRowWithContent: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingRight: 10,
    paddingTop: 10,
  },
  flexRowWithContent1: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  profileImageCircle: {
    width: widthUtils(90, 90).width,
    height: widthUtils(90, 90).height,
    borderWidth: 0,
    backgroundColor: "#fff",
    borderRadius: 50,
    padding: 10,
  },
  profileImage: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  customerInfoPanel: {
    marginLeft: 20,
  },
  uniqueHeaderTextStyle: {
    padding: 0,
    margin: 0,
    fontSize: fontSize(20),
    fontWeight: "900",
    fontFamily: "Archivo Black, sans-serif",
    color: "white",
  },
  elegantText: {
    padding: 0,
    margin: 0,
    marginTop: widthUtils(6, 6).height,
    fontSize: fontSize(16),
    fontWeight: "900",
    fontFamily: "PingFang SC",
    lineHeight: 22,
    color: "white",
  },
  transactionSummaryBox: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: widthUtils(6, 6).height,
  },
  svgContainer: {
    display: "flex",
    width: widthUtils(24, 24).width,
    height: widthUtils(24, 24).height,
    color: "#ffffff",
    marginRight: 8,
  },
  soldeTextDisplayStyle: {
    padding: 0,
    margin: 0,
    marginLeft: 3,
    fontSize: fontSize(20),
    fontWeight: "900",
    fontFamily: "PingFang SC",
    lineHeight: 24,
    color: "#f4f6fb",
    textShadowColor: "#000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  imageContainerWithText: {
    width: widthUtils(16, 24).width,
    height: widthUtils(16, 24).height,
    borderWidth: 0,
    resizeMode: "cover",
  },
  financialInfoContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginLeft: 3,
  },
  financialInfoContainerWithFlag: {
    marginLeft: 10,
  },
  whiteTextHeading: {
    padding: 0,
    margin: 0,
    fontSize: fontSize(16),
    fontWeight: "500",
    fontFamily: "PingFang SC",
    lineHeight: 22,
    color: "white",
  },
  svgContainer1: {
    width: widthUtils(24, 24).width,
    height: widthUtils(24, 24).height,
    marginLeft: 11,
    color: "#ffffff",
  },
  gradientCardContainer: {
    position: "absolute",
    bottom: 9,
    left: 19,
    right: 19,
    borderRadius: 10,
    zIndex: 1,
  },
  promoCardContainer2: {
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "flex-start",
    height: widthUtils(100, 100).height,
    paddingRight: 9.5,
    paddingBottom: 15,
    paddingLeft: 9,
    width: "100%",
  },
  promoCardContainerVip: {
    width: "100%",
    paddingTop: 5,
    paddingLeft: 10,
    paddingRight: 10,
    height: "100%",
  },
  VipCard: {
    width: "100%",
    height: "50%",
    flexDirection: "row",
  },
  Vip: {
    width: "35%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  progressBar: {
    width: "65%",
    marginLeft: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  progressBarFill: {
    width: "100%",
    height: "50%",
  },
  progressBarText: {
    fontSize: fontSize(16),
    fontWeight: "900",
    fontFamily: "Segoe UI",
    color: "#fcca80",
  },
  progressBarContainer: {
    width: "100%",
    height: 3,
    backgroundColor: "#d9d9d9",
    position: "relative",
  },
  progressBarFilled: {
    position: "absolute",
    top: 0,
    left: 0,
    height: "100%",
    backgroundColor: "#f2cc86",
  },
  progressBarEndDot: {
    position: "absolute",
    top: -2,
    marginLeft: -4,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#f2cc86",
    borderWidth: 1,
    borderColor: "#fff",
  },
  vipExplanation: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
  },
  vipExplanationText: {
    width: "70%",
    height: "100%",
  },
  vipExplanationText1: {
    fontSize: fontSize(12),
    padding: 5,
    color: "#fff",
  },
  nextVipText: {
    color: "#f8cb7a",
    fontWeight: "900",
    fontStyle: "italic",
  },
  vipExplanationButton: {
    width: "30%",
    height: "60%",
    backgroundColor: "#ffd89b",
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
  },
  vipExplanationButtonText: {
    fontSize: fontSize(14),
  },
  vipContainer: {
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
  },
  VipImg: {
    width: widthUtils(28, 28).width,
    height: widthUtils(28, 28).height,
  },
  discountPercentageTextStyle: {
    position: "absolute",
    fontSize: fontSize(12),
    fontFamily: "Segoe UI",
    fontWeight: "900",
    fontStyle: "italic",
    color: "#4e2000",
    textAlign: "center",
  },
  productInfoContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  imageWithTextRatio: {
    width: widthUtils(23.5, 56).width,
    height: widthUtils(23.5, 56).height,
  },
  goldenItalicHeading: {
    fontSize: fontSize(34),
    fontWeight: "900",
    fontStyle: "italic",
    color: "#f8cb7a",
  },
  discountSectionContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "flex-start",
    marginLeft: 4,
  },
  discountAmountContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  negativeMarginTopDiscountPercentage: {
    marginTop: -22,
  },
  nestedContentContainer: {
    marginTop: -25,
  },
  negativeMarginTop2: {
    marginTop: -36,
  },
  imageContainer2: {
    width: widthUtils(36, 36).width,
    height: widthUtils(36, 36).height,
  },
  negativeMarginTop1: {
    marginTop: -36,
  },
  imgStyleF62: {
    width: "100%",
    height: widthUtils(36, 36).height,
  },
  discountStatusContainer: {
    paddingRight: 7,
    paddingLeft: 7,
    marginTop: -23,
  },
  discountStatusLabel: {
    padding: 0,
    margin: 0,
    fontSize: fontSize(10),
    fontWeight: "600",
    fontStyle: "italic",
    fontFamily: "Segoe UI",
    color: "#4e2000",
  },
  productSummaryBlock: {
    paddingTop: 4,
    paddingBottom: 6.5,
    marginLeft: 16,
  },
  goldenTextHeading: {
    padding: 0,
    margin: 0,
    fontSize: fontSize(13),
    fontWeight: "600",
    fontFamily: "PingFang SC",
    color: "#f8cb7a",
  },
  negativeMarginTop: {
    marginTop: -0.5,
  },
  horizontalLineWidget: {
    width: widthUtils(4, 235).width,
    height: widthUtils(4, 235).height,
  },
  promoCardContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "flex-start",
    height: widthUtils(34, 34).height,
    marginTop: 6,
  },
  promoCardContainer1: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "flex-end",
  },
  pingfangScTextWhite: {
    padding: 0,
    margin: 0,
    fontSize: fontSize(11),
    fontWeight: "400",
    fontFamily: "PingFang SC",
    lineHeight: 17,
    color: "white",
    textAlign: "left",
    letterSpacing: -0.1,
  },
  promoDetailsContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: -17,
  },
  goldenLabel: {
    width: "30%",
    padding: 0,
    margin: 0,
    fontSize: fontSize(12),
    fontWeight: "900",
    fontFamily: "MiSans",
    lineHeight: 15,
    color: "#f5c164",
  },
  goldenText: {
    width: "70%",
    padding: 0,
    paddingRight: 24,
    paddingLeft: 37,
    margin: 0,
    fontSize: fontSize(12),
    fontWeight: "900",
    fontFamily: "MiSans",
    lineHeight: 15,
    color: "#f5c164",
  },
  goldenGradientBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingRight: 6,
    paddingLeft: 6,
    marginLeft: 11,
    backgroundColor: "#F5C164",
    borderRadius: 50,
  },
  featuredText: {
    padding: 0,
    margin: 0,
    fontSize: fontSize(11),
    fontWeight: "700",
    fontFamily: "Source Han Sans CN",
    color: "#473c30",
  },
  verticalCenterImageGallery: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "center",
    paddingTop: 21.5,
    paddingRight: 20,
    paddingLeft: 20,
    backgroundColor: "#f0f0f0",
  },
  cardContainer1: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "flex-start",
    paddingTop: 14,
    paddingRight: 9,
    paddingBottom: 14,
    paddingLeft: 10,
    backgroundColor: "white",
    borderRadius: 10,
  },
  imageContainer: {
    height: widthUtils(212, 212).height,
    borderWidth: 0,
    resizeMode: "cover",
  },
  cardContainer: {
    paddingTop: 15,
    paddingRight: 11,
    paddingBottom: 17,
    paddingLeft: 11,
    marginTop: 20,
    backgroundColor: "white",
    borderRadius: 10,
  },
  imageContainer1: {
    width: "100%",
    height: widthUtils(228, 228).height,
    borderWidth: 0,
    resizeMode: "cover",
  },
  groupContainer: {
    padding: 20,
  },
  groupItemList: {
    width: "100%",
    alignItems: "center",
    backgroundColor: "white",
  },
  groupItemTitle: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
  },
  groupItemTitleText: {
    fontSize: fontSize(18),
    fontWeight: "600",
    color: "#000",
  },
  groupItemTitleTextTout: {
    fontSize: fontSize(16),
    fontWeight: "400",
    color: "#8f8684",
    flexDirection: "row",
    alignItems: "center",
  },
  groupItemTitleTextTout1: {
    marginRight: 3,
    fontSize: fontSize(16),
    fontWeight: "400",
    color: "#8f8684",
    flexDirection: "row",
    alignItems: "center",
  },
  groupItem: {
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
    marginTop: 25,
  },
  groupItemContent: {
    width: "23%",
    borderRadius: 8,
    marginLeft: 5,
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "column",
    marginBottom: 10,
  },
  groupItemContentText: {
    fontSize: fontSize(14),
    fontWeight: "400",
    color: "#8f8684",
    width: "100%",
    textAlign: "center",
    marginTop: 5,
  },
  groupItemContentIcon: {
    width: widthUtils(50, 50).width,
    height: widthUtils(50, 50).height,
  },
  groupItemContentIconImg: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  notLoggedInContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 40,
  },
  loginButton: {
    backgroundColor: "#FF6F30",
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderRadius: 20,
    marginTop: 20,
  },
  loginButtonText: {
    color: "#fff",
    fontSize: fontSize(16),
    fontWeight: "600",
  },
  fixedLoginButton: {
    backgroundColor: "#FF6F30",
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderRadius: 20,
    position: "absolute",
    bottom: 20,
    alignSelf: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  avatarTouchable: {
    position: "relative",
  },
  profileImageLoading: {
    opacity: 0.5,
  },
  uploadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  uploadingText: {
    fontSize: fontSize(24),
    fontWeight: "bold",
    color: "#fff",
  },
  
  // Balance Card
  balanceCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 24,
    marginHorizontal: 10,
    marginTop: 12,
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#FF6F30',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 81, 0, 0.1)',
  },
  balanceCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    gap: 8,
  },
  balanceCardTitle: {
    color: '#666',
    fontSize: fontSize(14),
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  balanceAmountContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
    marginBottom: 24,
    gap: 4,
  },
  balanceCurrency: {
    color: '#999',
    fontSize: fontSize(20),
    fontWeight: '600',
    textShadowColor: 'rgba(153, 153, 153, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  balanceAmount: {
    color: '#000',
    fontSize: fontSize(36),
    fontWeight: '800',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  balanceActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: 16,
  },
  balanceButton: {
    width: '47%', // 固定宽度，确保两个按钮完全一致
    backgroundColor: '#FF6F30',
    minHeight: 40,
    borderRadius: 25,
    elevation: 3,
    shadowColor: '#FF6F30',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  balanceButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 8, // 进一步减少内边距
    gap: 6, // 减少图标和文本间距
    flex: 1, // 占满按钮空间
    width: '100%', // 确保内容宽度一致
  },
  balanceButtonText: {
    color: '#fff',
    fontSize: fontSize(14), // 稍微减小字体以适应更小空间
    fontWeight: '600',
    letterSpacing: 0.3,
    flexShrink: 1, // 允许文本在需要时收缩
    textAlign: 'center', // 确保文本居中
  },

  // Section Cards (Orders, Services)
  sectionCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginHorizontal: 10,
    marginTop: 12,
    padding: 12,
  },  
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: fontSize(18),
    fontWeight: 'bold',
    color: '#333',
  },
  sectionAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionAllButtonText: {
    fontSize: fontSize(14),
    color: '#8f8684',
    marginRight: 4,
  },
  sectionContent: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  sectionItem: {
    alignItems: 'center',
    width: '20%', // 5 items per row
  },
  sectionItemIcon: {
    fontSize: 28,
    color: '#555555',
    marginBottom: 8,
  },
  sectionItemText: {
    fontSize: fontSize(12),
    color: '#666',
  },
  badgeContainer: {
    position: 'absolute',
    top: -5,
    right: 15,
    backgroundColor: '#FF6F30',
    borderRadius: 7.5,
    minWidth: 15,
    height: 15,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  badgeText: {
    color: '#fff',
    fontSize: fontSize(12),
    fontWeight: 'bold',
    paddingHorizontal: 5,
  },

  // Profile Header
  profileHeaderContainer: {
    paddingTop: 0,
    paddingBottom: 40,
    paddingHorizontal: 10,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingsButton: {
    paddingTop: 0, // Add padding to increase touchable area
  },
  profileInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  avatarContainer: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    fontWeight: 'bold',
  },
  avatarPlaceholder: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(255,255,255,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarPlaceholderText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  userInfo: {
    marginLeft: 16,
  },
  userName: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  userPhone: {
    color: '#fff',
    fontSize: 14,
    marginTop: 4,
    opacity: 0.9,
  },

  // VIP Card
  vipCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 10,
    marginTop: -20, // To overlap with the header
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  vipCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  vipCardTitle: {
    fontSize: 14,
    color: '#666',
  },
  vipLevelTag: {
    backgroundColor: 'white',
    color: 'red',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    fontWeight: 'bold',
    fontSize: 16,
    marginRight: 8,
  },
  vipCardLink: {
    fontSize: 12,
    color: '#999',
    marginTop: -10
  },
  vipProgressBarOuter: {
    height: 6,
    backgroundColor: '#f0f0f0',
    borderRadius: 3,
    marginTop: 12,
    overflow: 'hidden',
  },
  vipProgressBarInner: {
    height: '100%',
    backgroundColor: '#FF6F30',
    borderRadius: 3,
  },
  vipProgressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  vipProgressLabel: {
    fontSize: 10,
    color: '#999',
  },
  vipProgressPercentage: {
    fontSize: 10,
    color: '#999',
    position: 'absolute',
    alignSelf: 'center',
    left: '48%' // Adjust to center
  },
  vipBenefits: {
    fontSize: 12,
    color: '#999',
    marginTop: 8,
  },
  vipBenefitsHighlight: {
    fontSize: 12,
    color: '#000',
    fontWeight: 'bold',
  },
}); 