import { StyleSheet } from "react-native";
import fontSize from "../../../../utils/fontsizeUtils";
import { Styles } from "../types";

export const styles = StyleSheet.create<Styles>({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  safeAreaContent: {
    flex: 1,
    paddingTop: 0,
  },
  container: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    borderBottomWidth: 0.5,
    borderBottomColor: "#f0f0f0",
  },
  title: {
    fontSize: fontSize(18),
    fontWeight: "700",
    color: "#1a1a1a",
    letterSpacing: -0.3,
  },
  orderStatus: {
    paddingHorizontal: 16,
    marginTop: 12,
  },
  orderStatusContent: {
    backgroundColor: "#fff",
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 2,
  },
  orderStatusTitle: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderColor: "#f8f8f8",
  },
  orderStatusTitleText: {
    fontSize: fontSize(16),
    fontWeight: "700",
    marginLeft: 12,
    color: "#1a1a1a",
    letterSpacing: -0.2,
  },
  orderStatusContentPreview: {
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  productItem: {
    flexDirection: "row",
    width: "100%",
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderColor: "#f8f8f8",
  },
  productItemImage: {
    width: 60,
    height: 60,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#f8f8f8",
  },
  productItemInfo: {
    flex: 1,
    paddingLeft: 16,
    justifyContent: "space-between",
  },
  productItemNum: {
    alignItems: "flex-end",
    justifyContent: "center",
    minWidth: 40,
  },
  productItemNumText: {
    fontSize: fontSize(14),
    color: "#666",
    fontWeight: "500",
  },
  productItemInfoName: {
    marginBottom: 6,
  },
  productItemInfoNameText: {
    fontSize: fontSize(15),
    fontWeight: "600",
    color: "#1a1a1a",
    lineHeight: fontSize(20),
  },
  productItemInfoSkuText: {
    fontSize: fontSize(13),
    color: "#999",
    marginBottom: 2,
    lineHeight: fontSize(18),
  },
  productItemInfoSku: {
    marginBottom: 8,
  },
  productItemInfoPrice: {
    alignItems: "flex-start",
  },
  orderStatusContentPreviewInformation: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: 20,
  },

  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
  },
  orderId: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    width: "100%",
  },
  orderIdText: {
    color: "#666",
    fontSize: fontSize(14),
    fontWeight: "500",
    flex: 1,
  },
  orderIdText1: {
    fontSize: fontSize(14),
    fontWeight: "600",
    color: "#1a1a1a",
    flex: 1,
    textAlign: "right",
  },
  TotalText: {
    color: "#FF5100",
    fontSize: fontSize(18),
    fontWeight: "700",
    flex: 1,
  },
  TotalPrice: {
    color: "#FF5100",
    fontSize: fontSize(18),
    fontWeight: "700",
    flex: 1,
    textAlign: "right",
  },
  warehouse: {
    flex: 1,
    paddingRight: 10,
  },
  recipientTitle: {
    marginBottom: 8,
  },
  recipientPhoneContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  recipient: {
    flex: 1,
    paddingLeft: 10,
  },
  orderStatusContentPreviewInformationText: {
    fontSize: fontSize(15),
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 12,
  },
  warehousePhone: {
    padding: 12,
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e8e8e8",
  },
  warehousePhoneText: {
    fontSize: fontSize(13),
    fontWeight: "500",
    color: "#666",
    lineHeight: fontSize(18),
  },
  warehousePhoneTextContainer: {
    marginRight: 8,
  },
  recipientName: {
    fontSize: fontSize(15),
    fontWeight: "600",
    color: "#1a1a1a",
    marginBottom: 8,
  },
  recipientPhone: {
    fontSize: fontSize(14),
    fontWeight: "500",
    color: "#666",
    marginLeft: 6,
  },
  dottedLine: {
    height: 1,
    marginVertical: 16,
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: "#e8e8e8",
  },
  orderRemakeText: {
    fontSize: fontSize(13),
    fontWeight: "500",
    color: "#999",
    marginTop: 8,
    lineHeight: fontSize(18),
  },
  addCard: {
    width: "100%",
    alignItems: "center",
    marginTop: 8,
  },
  addCardBox: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderWidth: 1.5,
    borderColor: "#0098ef",
    borderRadius: 12,
    backgroundColor: "#f0f8ff",
    flexDirection: "row",
    alignItems: "center",
  },
  addCardText: {
    fontSize: fontSize(15),
    fontWeight: "600",
    color: "#0098ef",
    marginLeft: 8,
  },
  bottomButtons: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 20,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
    gap: 12,
  },
  bottomButton1: {
    flex: 1,
    paddingVertical: 14,
    alignItems: "center",
    backgroundColor: "#f8f8f8",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e8e8e8",
  },
  bottomButton: {
    flex: 1,
    paddingVertical: 14,
    alignItems: "center",
    backgroundColor: "#FF5100",
    borderRadius: 12,
    shadowColor: "#FF5100",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  bottomButtonText: {
    fontSize: fontSize(16),
    fontWeight: "700",
    color: "#fff",
    letterSpacing: -0.2,
  },
  bottomButtonText1: {
    fontSize: fontSize(16),
    fontWeight: "600",
    color: "#666",
    letterSpacing: -0.2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "#00000080",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  modalTitle: {
    fontSize: fontSize(18),
    fontWeight: "700",
    color: "#1a1a1a",
  },
  closeButtonContainer: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "#f8f8f8",
  },
  closeButtonText: {
    fontSize: fontSize(18),
    color: "#666",
    fontWeight: "600",
  },
  tabContainer: {
    flexDirection: "row",
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  tab: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginRight: 20,
    position: "relative",
  },
  tabActive: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginRight: 20,
    position: "relative",
    borderBottomWidth: 2,
    borderBottomColor: "#FF5100",
  },
  tabText: {
    fontSize: fontSize(15),
    color: "#999",
    fontWeight: "500",
  },
  tabTextActive: {
    color: "#FF5100",
    fontWeight: "700",
  },
  underline: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: "#FF5100",
    borderRadius: 1,
  },
  paymentOptions: {
    maxHeight: 350,
  },
  cardContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    backgroundColor: "#fff",
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#f0f0f0",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  iconRow: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  imageContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  paymentIconContainer: {
    marginRight: 12,
  },
  paymentIcon: {
    fontSize: fontSize(24),
    marginRight: 8,
  },
  checkboxContainer: {
    position: "relative",
    width: fontSize(24),
    height: fontSize(24),
    justifyContent: "center",
    alignItems: "center",
  },
  checkmarkContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  currencyTitle: {
    fontSize: fontSize(14),
    color: "#666",
    marginBottom: 12,
    fontWeight: "600",
  },
  paypalExpandedContainer: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    marginTop: 8,
    marginBottom: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: "#e8e8e8",
  },
  paypalCurrencyContainer: {
    paddingVertical: 8,
  },
  currencyButtonsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 12,
    gap: 8,
  },
  currencyButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e8e8e8",
    backgroundColor: "#fff",
  },
  currencyButtonActive: {
    backgroundColor: "#fff4f0",
    borderColor: "#FF5100",
  },
  currencyButtonText: {
    fontSize: fontSize(14),
    color: "#666",
    fontWeight: "500",
  },
  currencyButtonTextActive: {
    color: "#FF5100",
    fontWeight: "700",
  },
  convertingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 12,
  },
  convertingText: {
    fontSize: fontSize(13),
    color: "#999",
    marginLeft: 8,
    fontWeight: "500",
  },
  convertedAmountContainer: {
    marginTop: 12,
    padding: 12,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e8e8e8",
  },
  convertedAmountLabel: {
    fontSize: fontSize(13),
    color: "#666",
    marginBottom: 4,
    fontWeight: "500",
  },
  convertedAmountValue: {
    fontSize: fontSize(16),
    fontWeight: "700",
    color: "#FF5100",
  },
  actionButtonsContainer: {
    marginTop: 24,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  actionButtons: {
    flexDirection: "row",
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e8e8e8",
    backgroundColor: "#f8f8f8",
    alignItems: "center",
  },
  confirmButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#FF5100",
    alignItems: "center",
    shadowColor: "#FF5100",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  confirmButtonDisabled: {
    backgroundColor: "#ccc",
    shadowOpacity: 0,
    elevation: 0,
  },
  buttonTextDark: {
    fontSize: fontSize(15),
    color: "#666",
    fontWeight: "600",
  },
  buttonTextWhite: {
    fontSize: fontSize(15),
    color: "#fff",
    fontWeight: "700",
  },
  operatorImage: {
    width: 80,
    height: 30,
    resizeMode: "contain",
    marginRight: 12,
  },
  mobileMoneyTextContainer: {
    width: "100%",
    marginTop: 4,
    alignItems: "flex-start",
    flexDirection: "row",
  },
  mobileMoneyImgContainer: {
    width: 60,
    height: 22,
    borderWidth: 0,
    marginRight: 8,
    borderRadius: 4,
    overflow: "hidden",
  },
  mobileMoneyImg: {
    width: 60,
    height: 22,
    borderWidth: 0,
  },
  mobileMoneyText: {
    fontSize: fontSize(12),
    color: "#999",
    fontWeight: "500",
  },
  outerContainer: {
    width: "100%",
  },
  flexContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: "white",
    borderRadius: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#f0f0f0",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  imageStyle: {
    width: 60,
    height: 22,
    marginRight: 12,
    borderRadius: 4,
  },
  verticalAlignEndContent: {
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  svgContainer: {
    width: 24,
    height: 24,
  },
  leftInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  blueBox: {
    flexDirection: "row",
    backgroundColor: "#4169e1",
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignItems: "center",
    borderRadius: 6,
  },
  balanceText: {
    marginLeft: 16,
    fontSize: fontSize(12),
    lineHeight: 16,
    fontWeight: "600",
    color: "#666",
  },
  modalPopup: {
    backgroundColor: "#fff",
    padding: 24,
    borderRadius: 16,
    width: "85%",
    maxWidth: 320,
    alignItems: "center",
  },
  modalWarningIcon: {
    alignItems: "center",
    marginBottom: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#fff5f5",
    justifyContent: "center",
  },
  modalPromptText: {
    fontSize: fontSize(16),
    color: "#1a1a1a",
    marginBottom: 24,
    textAlign: "center",
    lineHeight: fontSize(24),
    fontWeight: "600",
  },
  modalCancelPopup: {
    width: "85%",
    maxWidth: 320,
    padding: 24,
    alignItems: "center",
  },
  modalCancelText: {
    fontSize: fontSize(16),
    color: "#1a1a1a",
    marginVertical: 20,
    textAlign: "center",
    lineHeight: fontSize(24),
    fontWeight: "600",
  },
  modalCancelButtonsContainer: {
    flexDirection: "row",
    width: "100%",
    marginTop: 24,
    gap: 12,
  },
  modalCancelActionButton: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  modalCancelButtonOutline: {
    backgroundColor: "#f8f8f8",
    borderWidth: 1,
    borderColor: "#e8e8e8",
  },
  modalCancelButtonFilled: {
    backgroundColor: "#FF5100",
    shadowColor: "#FF5100",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  modalCancelButtonOutlineText: {
    fontSize: fontSize(15),
    color: "#666",
    fontWeight: "600",
  },
  modalCancelButtonFilledText: {
    fontSize: fontSize(15),
    color: "#FFF",
    fontWeight: "700",
  },
  orderStatusTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  orderInfoHeader: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    justifyContent: "space-between",
  },
  checkPaymentButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#fff4f0",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FF5100",
  },
  checkPaymentText: {
    fontSize: fontSize(13),
    color: "#FF5100",
    fontWeight: "600",
  },
  cashOnDeliveryTagContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 4,
  },
  cashOnDeliveryTag: {
    backgroundColor: "#FFF3E0",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#FF5100",
  },
  cashOnDeliveryText: {
    fontSize: fontSize(12),
    color: "#FF6000",
    fontWeight: "500",
  },
  orderInfoItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    width: "100%",
  },
  orderInfoLabel: {
    color: "#666",
    fontSize: fontSize(14),
    fontWeight: "500",
    flex: 1,
  },
  orderInfoValue: {
    fontSize: fontSize(14),
    fontWeight: "600",
    color: "#1a1a1a",
    flex: 1,
    textAlign: "right",
  },
  shippingTypeContainer: {
    flex: 1,
    alignItems: "flex-end",
  },
  shippingTypeText: {
    fontSize: fontSize(13),
    fontWeight: "600",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    overflow: "hidden",
  },
  shippingTypeSea: {
    backgroundColor: "#e8f4f8",
    color: "#1976d2",
  },
  shippingTypeAir: {
    backgroundColor: "#fff3e0",
    color: "#f57c00",
  },
  deliveryInfoContainer: {
    gap: 20,
  },
  warehouseSection: {
    marginBottom: 20,
  },
  recipientSection: {
    marginBottom: 0,
  },
  sectionTitle: {
    fontSize: fontSize(15),
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 12,
  },
  warehouseInfo: {
    gap: 8,
  },
  warehouseAddress: {
    fontSize: fontSize(14),
    fontWeight: "500",
    color: "#1a1a1a",
    lineHeight: fontSize(20),
  },
  contactNotice: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e8e8e8",
    gap: 6,
  },
  contactNoticeText: {
    fontSize: fontSize(12),
    fontWeight: "500",
    color: "#666",
    lineHeight: fontSize(16),
  },
  recipientInfo: {
    gap: 8,
  },
  contactMethods: {
    gap: 6,
  },
  contactItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  contactLabel: {
    fontSize: fontSize(13),
    fontWeight: "500",
    color: "#666",
  },
  contactText: {
    fontSize: fontSize(13),
    fontWeight: "500",
    color: "#666",
  },
  productsList: {
    gap: 0,
  },
  productImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    borderRadius: 12,
  },
  productPriceContainer: {
    alignItems: "flex-start",
  },
  productPrice: {
    color: "#FF5100",
    fontSize: fontSize(16),
    fontWeight: "700",
  },
  addToCartButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderWidth: 1.5,
    borderColor: "#0098ef",
    borderRadius: 12,
    backgroundColor: "#f0f8ff",
    marginTop: 8,
    gap: 8,
  },
  addToCartText: {
    fontSize: fontSize(15),
    fontWeight: "600",
    color: "#0098ef",
  },
  priceBreakdown: {
    gap: 0,
  },
  priceItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    width: "100%",
  },
  priceLabel: {
    color: "#666",
    fontSize: fontSize(14),
    fontWeight: "500",
    flex: 1,
  },
  priceValue: {
    fontSize: fontSize(14),
    fontWeight: "600",
    color: "#1a1a1a",
    flex: 1,
    textAlign: "right",
  },
  totalSection: {
    gap: 8,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  totalLabel: {
    color: "#FF5100",
    fontSize: fontSize(18),
    fontWeight: "700",
    flex: 1,
  },
  totalPrice: {
    color: "#FF5100",
    fontSize: fontSize(18),
    fontWeight: "700",
    flex: 1,
    textAlign: "right",
  },
  shippingNote: {
    fontSize: fontSize(13),
    fontWeight: "500",
    color: "#999",
    lineHeight: fontSize(18),
  },
  
  // 运费险样式
  shippingInsuranceContainer: {
    marginTop: 8,
    borderWidth: 2,
    borderColor: "#4CAF50",
    borderRadius: 8,
    backgroundColor: "#f8fff8",
    padding: 12,
  },
  shippingInsuranceContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  shippingInsuranceIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#FF5722",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  shippingInsuranceText: {
    fontSize: fontSize(14),
    fontWeight: "500",
    color: "#333",
    flex: 1,
  },
  shippingInsuranceAmount: {
    fontSize: fontSize(14),
    fontWeight: "600",
    color: "#333",
  },
}); 