import { MySetting } from '../services/api/setting';

export type RootStackParamList = {
  CountrySelect: undefined;
  Login: undefined;
  EmailLogin: undefined;
  MainTabs: undefined;
  Search: undefined;
  SearchResult: { keyword?: string, category_id?: number, formData?: FormData };
  ImageSearchResultScreen: { image?: string, type?: number };
  ProductDetail: { offer_id: string; price?: number; searchKeyword?: string };
  RelatedProductsScreen: { product_id: string; product_name: string };
  ChatScreen: {
    product_id?: string;
    product_image_urls?: string[];
    subject_trans?: string;
    min_price?: number;
    offer_id?: string;
  };
  ProductChatScreen: {
    product_image_urls?: string[];
    subject_trans?: string;
    min_price?: number;
    offer_id?: string;
  };
  Balance: undefined;
  ShippingDetailsSection: undefined;
  InquiryScreen: undefined;
  Recipient: { items: { cart_item_id: number }[] };
  AddRess: undefined;
  SettingList: undefined;
  CountrySetting: { mySetting?: MySetting };
  MyAddress: undefined;
  CartScreen: undefined;
  PaymentSuccessScreen: { paymentId?: string; PayerID?: string };
  PayError: undefined;
  OfflinePayment: undefined;
  MyAccount: undefined;
  Google: undefined;
  ConfirmOrder: undefined;
  Pay: undefined;
  Status: undefined;
  OrderDetails: undefined;
  TikTokScreen: undefined;
  BrowseHistoryScreen: undefined;
  Collection: undefined;
  MemberIntroduction: undefined;
  CompanyScreen: undefined;
  PreviewAddress: undefined;
  AddressList: undefined;
  AddAddress: undefined;
  EditAddress: undefined;
  PaymentMethod: undefined;
  ShippingFee: undefined;
  PreviewOrder: undefined;
  ForgotPhonePassword: undefined;
  PhoneLoginScreen: undefined;
  WhatsAppLoginScreen: undefined;
  Info: undefined;
  ChangePassword: undefined;
  PrivacyPolicyScreen: undefined;
  TermsOfUseScreen: undefined;
  LoginPromptScreen: { title?: string; message?: string; icon?: string };
  EmailOtp: { email: string };
};
