import { StyleSheet, Platform } from 'react-native';
import fontSize from '../../utils/fontsizeUtils';
import widthUtils from '../../utils/widthUtils';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#fff",
  },
  safeAreaContent: {
    flex: 1,
    paddingTop: Platform.OS === "android" ? 0 : 0,
  },
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  scrollView: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  headerBox: {
    width: "100%",
    padding: 10,
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  backIcon: {
    width: "5%",
    alignItems: "flex-end",
  },
  search: {
    width: "85%",
    height: 40,
    paddingHorizontal: 15,
    paddingVertical: 8,
    backgroundColor: "#f4f4f4",
    borderWidth: 0.5,
    borderColor: "black",
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginLeft: 5,
    marginRight: 10,
  },
  searchText: {
    fontSize: fontSize(14),
    color: "black",
    fontWeight: "400",
    textAlignVertical: "center",
  },
  cartIcon: {
    alignItems: "center",
    marginRight: 10,
    justifyContent: "center",
    flexDirection: "row",
  },
  scrollViewContent: {},
  productLayoutContainer: {
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "flex-start",
    width: "100%",
    backgroundColor: "#f5f5f5",
  },
  productContentContainer: {
    backgroundColor: "#f5f5f5",
  },
  imageCarouselContainer: {
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "center",
    width: "100%",
    backgroundColor: "#f5f5f5",
  },
  productInfoCard: {
    width: "100%",
    height: 130,
    padding: 16,
    paddingHorizontal: 10,
    paddingBottom: 10,
    backgroundColor: "white",
  },
  productTitle: {
    width: "100%",
    marginTop: -10,
    fontWeight: "500",
    fontSize: fontSize(16),
    lineHeight: 20,
    color: "black",
    textAlign: "left",
  },
  productPriceWrapper: {
    backgroundColor: "white",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  productPriceContainer: {
    flex: 1,
  },
  salesInfoContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 0,
    justifyContent: "flex-start",
  },
  highlightedText: {
    marginTop: 10,
    fontWeight: "600",
    fontSize: fontSize(20),
    color: "#ff5100",
    marginLeft: 0,
  },
  currencyText: {
    marginTop: 10,
    fontWeight: "700",
    fontSize: fontSize(14),
    marginLeft: 1.25,
    color: "#ff5100",
    lineHeight: 28,
  },
  salesCountLabel: {
    marginTop: 6.75,
    fontWeight: "600",
    fontSize: fontSize(14),
    color: "#7c7c7c",
  },
  priceLabel: {
    marginTop: 10,
    fontWeight: "600",
    fontSize: fontSize(12),
    color: "#9a9a9a",
    textDecorationLine: "line-through",
    marginLeft: 8,
    lineHeight: 28,
  },
  discountInfoContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    marginLeft: 10,
    height: 20,
  },
  discountBadge: {
    fontStyle: "italic",
    fontWeight: "900",
    fontSize: fontSize(11),
    color: "#4e2000",
    backgroundColor: "#FFE4D6",
    padding: 3,
    borderRadius: 3,
  },
  vipStatusNumeric: {
    fontStyle: "italic",
    fontWeight: "900",
    fontSize: fontSize(18),
    color: "#f1c355",
    textAlign: "center",
    marginLeft: 2,
  },
  productDetailsContainer: {
    flexDirection: "column",
    gap: 10,
    alignItems: "stretch",
    justifyContent: "flex-start",
    width: "100%",
    padding: 10,
    paddingHorizontal: 10,
    paddingBottom: 10,
    marginTop: 10,
    backgroundColor: "white",
  },
  productAttributesWrapper: {
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "flex-start",
  },
  attributesContainer: {},
  attributeLabel: {
    fontWeight: "600",
    fontSize: fontSize(16),
    lineHeight: 20,
    color: "black",
  },
  horizontalFlexContainer: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: 8,
  },
  imageContainer: {
    width: widthUtils(40, 40).width,
    height: widthUtils(40, 40).height,
    borderRadius: 5,
  },
  expandIconContainer: {
    alignSelf: "flex-end",
    width: widthUtils(18, 18).width,
    height: widthUtils(18, 18).height,
  },
  sizeButton: {
    alignItems: "center",
    justifyContent: "center",
    height: widthUtils(30, 40).height,
    paddingHorizontal: 11,
    backgroundColor: "#efefef",
    borderRadius: 5,
    marginBottom: 10,
  },
  priceInfoVip: {
    width: widthUtils(21, 63).width,
    height: widthUtils(21, 63).height,
    marginLeft: 8,
    alignSelf: "flex-start",
  },
  priceInfoVipImg: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  sizeButtonText: {
    fontWeight: "400",
    fontSize: fontSize(14),
    color: "#373737",
    lineHeight: widthUtils(30, 40).height,
  },
  selectedSizeButton: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#000000",
  },
  selectedSizeText: {
    color: "#000000",
    fontWeight: "400",
  },
  expandButton: {
    alignItems: "center",
    justifyContent: "center",
    height: widthUtils(38, 38).height,
    paddingHorizontal: 11,
    fontWeight: "600",
    fontSize: fontSize(14),
    color: "#ff5100",
    borderRadius: 5,
    lineHeight: widthUtils(40, 40).height,
    marginBottom: 10,
    backgroundColor: "#efefef",
  },
  expandButtonText: {
    color: "#b7b7b7",
    fontWeight: "600",
  },
  storeRecommendationsContainer: {
    width: "100%",
    padding: 10,
    paddingHorizontal: 10,
    paddingBottom: 19,
    marginTop: 8,
    backgroundColor: "white",
  },
  storeInfoContainer: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  storeSectionTitle: {
    fontWeight: "600",
    fontSize: fontSize(16),
    lineHeight: 20,
    color: "black",
  },
  storeMoreLink: {
    fontWeight: "600",
    fontSize: fontSize(10),
    color: "black",
  },
  productGridContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    marginTop: 12,
    paddingRight: 10,
  },
  productCard: {
    width: widthUtils(115, 90).width,
    height: widthUtils(140, 90).height,
    marginRight: 10,
  },
  cardContainerWithPrice: {
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "center",
    width: "100%",
    backgroundColor: "#e0e0e0",
    borderRadius: 5,
  },
  imageContainerCompact: {
    height: widthUtils(90, 90).height,
    width: widthUtils(90, 90).width,
    borderRadius: 8,
  },
  priceContainerFlex: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: 2,
  },
  productPrice: {
    fontWeight: "600",
    fontSize: fontSize(10),
    lineHeight: 20,
    color: "#ff5100",
  },
  smallCurrencyText: {
    fontWeight: "700",
    fontSize: fontSize(10),
    marginLeft: 1.25,
    color: "#ff5100",
  },
  productTitleSimilar: {
    marginTop: 2,
    fontWeight: "400",
    fontSize: fontSize(10),
    lineHeight: 12,
    color: "#333",
    textAlign: "left",
  },
  activeIndexText: {
    color: "white",
    fontSize: fontSize(12),
    width: widthUtils(26, 50).width,
    height: widthUtils(26, 50).height,
    textAlign: "center",
    lineHeight: widthUtils(26, 50).height + 2,
  },
  colorImageContainer: {
    padding: 2,
    borderRadius: 5,
  },
  selectedColorImageContainer: {
    backgroundColor: "#f5f5f5",
    borderWidth: 1,
    borderColor: "#000000",
  },
  fixedBottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 100,
    height: widthUtils(60, 60).height,
  },
  storeIconButton: {
    width: widthUtils(35, 35).width,
    height: widthUtils(35, 35).height,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 17.5,
    backgroundColor: "black",
    marginRight: 10,
  },
  chatNowButton: {
    flex: 1,
    height: widthUtils(35, 35).height,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 0,
    borderRadius: 21,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "black",
    marginRight: 8,
  },
  chatNowText: {
    fontSize: fontSize(14),
    color: "#333",
    fontWeight: "500",
  },
  addToCartButton: {
    flex: 1,
    height: widthUtils(35, 35).height,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 0,
    borderRadius: 21,
    backgroundColor: "#FF5722",
    marginLeft: 8,
  },
  addToCartText: {
    fontSize: fontSize(14),
    color: "#fff",
    fontWeight: "500",
  },
  bottomSheetOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "flex-end",
    zIndex: 200,
  },
  backgroundOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  bottomSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: "85%",
    zIndex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  loadingText: {
    marginTop: 10,
    fontSize: fontSize(16),
    color: "#666",
  },
  skeletonBox: {
    backgroundColor: "#e0e0e0",
    height: widthUtils(90, 90).height,
    width: widthUtils(90, 90).width,
    borderRadius: 5,
  },
  skeletonText: {
    height: 16,
    backgroundColor: "#e0e0e0",
    borderRadius: 3,
  },
  imagePickerOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
  },
  imagePickerText: {
    fontSize: fontSize(10),
    color: "#333",
    marginLeft: 10,
  },
  imagePickerDivider: {
    height: 1,
    backgroundColor: "#eee",
    marginHorizontal: 20,
  },
  imagePickerCancelButton: {
    alignItems: "center",
    paddingVertical: 15,
    borderTopWidth: 1,
    borderTopColor: "#eee",
    marginTop: 10,
  },
  imagePickerCancelText: {
    fontSize: fontSize(16),
    color: "#333",
  },
  productDetailsSection: {
    width: "100%",
    marginTop: 8,
    backgroundColor: "white",
    padding: 10,
    paddingLeft: 0,
    paddingBottom: 19,
  },
  productDetailsSectionTitle: {
    fontWeight: "600",
    fontSize: fontSize(16),
    lineHeight: 20,
    color: "black",
    paddingLeft: 10,
    marginBottom: 12,
  },
});